### ISSUE TITLE
Support for laravel 6.x ?

### ISSUE THREAD

**Issue by cacholong** [maximkou/laravel-opcache-clear#2]
Hi,

Could you please add support for laravel 6.x?

Regards, Matthijs

**Comment by maximkou** [comment]
Hi! 
I haven't plans for adding support of laravel 6, because this package actuality is lost - he isnt needed anymore in most cases.

Could you tell, whats your problem? Maybe I can help you in any way?

**Comment by maximkou** [comment]
Closed, because haven't activity a month.
